# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zw/blend

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zw/blend

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zw/blend/CMakeFiles /home/zw/blend//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zw/blend/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vertex_texture

# Build rule for target.
vertex_texture: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vertex_texture
.PHONY : vertex_texture

# fast build rule for target.
vertex_texture/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/build
.PHONY : vertex_texture/fast

#=============================================================================
# Target rules for targets named single_vertex_texture_shader

# Build rule for target.
single_vertex_texture_shader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 single_vertex_texture_shader
.PHONY : single_vertex_texture_shader

# fast build rule for target.
single_vertex_texture_shader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/build
.PHONY : single_vertex_texture_shader/fast

#=============================================================================
# Target rules for targets named blending

# Build rule for target.
blending: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blending
.PHONY : blending

# fast build rule for target.
blending/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/build
.PHONY : blending/fast

#=============================================================================
# Target rules for targets named logicop

# Build rule for target.
logicop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logicop
.PHONY : logicop

# fast build rule for target.
logicop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/build
.PHONY : logicop/fast

#=============================================================================
# Target rules for targets named template

# Build rule for target.
template: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 template
.PHONY : template

# fast build rule for target.
template/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/build
.PHONY : template/fast

#=============================================================================
# Target rules for targets named basicPoints

# Build rule for target.
basicPoints: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 basicPoints
.PHONY : basicPoints

# fast build rule for target.
basicPoints/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/build
.PHONY : basicPoints/fast

#=============================================================================
# Target rules for targets named depth_test

# Build rule for target.
depth_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 depth_test
.PHONY : depth_test

# fast build rule for target.
depth_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/build
.PHONY : depth_test/fast

#=============================================================================
# Target rules for targets named feed_back

# Build rule for target.
feed_back: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 feed_back
.PHONY : feed_back

# fast build rule for target.
feed_back/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/build
.PHONY : feed_back/fast

#=============================================================================
# Target rules for targets named complex

# Build rule for target.
complex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 complex
.PHONY : complex

# fast build rule for target.
complex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/build
.PHONY : complex/fast

#=============================================================================
# Target rules for targets named multi_vertex_texture_shader

# Build rule for target.
multi_vertex_texture_shader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 multi_vertex_texture_shader
.PHONY : multi_vertex_texture_shader

# fast build rule for target.
multi_vertex_texture_shader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/build
.PHONY : multi_vertex_texture_shader/fast

basicPoints.o: basicPoints.cpp.o
.PHONY : basicPoints.o

# target to build an object file
basicPoints.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/basicPoints.cpp.o
.PHONY : basicPoints.cpp.o

basicPoints.i: basicPoints.cpp.i
.PHONY : basicPoints.i

# target to preprocess a source file
basicPoints.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/basicPoints.cpp.i
.PHONY : basicPoints.cpp.i

basicPoints.s: basicPoints.cpp.s
.PHONY : basicPoints.s

# target to generate assembly for a file
basicPoints.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/basicPoints.cpp.s
.PHONY : basicPoints.cpp.s

blending.o: blending.cpp.o
.PHONY : blending.o

# target to build an object file
blending.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/blending.cpp.o
.PHONY : blending.cpp.o

blending.i: blending.cpp.i
.PHONY : blending.i

# target to preprocess a source file
blending.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/blending.cpp.i
.PHONY : blending.cpp.i

blending.s: blending.cpp.s
.PHONY : blending.s

# target to generate assembly for a file
blending.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/blending.cpp.s
.PHONY : blending.cpp.s

complex.o: complex.cpp.o
.PHONY : complex.o

# target to build an object file
complex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/complex.cpp.o
.PHONY : complex.cpp.o

complex.i: complex.cpp.i
.PHONY : complex.i

# target to preprocess a source file
complex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/complex.cpp.i
.PHONY : complex.cpp.i

complex.s: complex.cpp.s
.PHONY : complex.s

# target to generate assembly for a file
complex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/complex.cpp.s
.PHONY : complex.cpp.s

depth_test.o: depth_test.cpp.o
.PHONY : depth_test.o

# target to build an object file
depth_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/depth_test.cpp.o
.PHONY : depth_test.cpp.o

depth_test.i: depth_test.cpp.i
.PHONY : depth_test.i

# target to preprocess a source file
depth_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/depth_test.cpp.i
.PHONY : depth_test.cpp.i

depth_test.s: depth_test.cpp.s
.PHONY : depth_test.s

# target to generate assembly for a file
depth_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/depth_test.cpp.s
.PHONY : depth_test.cpp.s

feed_back.o: feed_back.cpp.o
.PHONY : feed_back.o

# target to build an object file
feed_back.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/feed_back.cpp.o
.PHONY : feed_back.cpp.o

feed_back.i: feed_back.cpp.i
.PHONY : feed_back.i

# target to preprocess a source file
feed_back.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/feed_back.cpp.i
.PHONY : feed_back.cpp.i

feed_back.s: feed_back.cpp.s
.PHONY : feed_back.s

# target to generate assembly for a file
feed_back.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/feed_back.cpp.s
.PHONY : feed_back.cpp.s

logicop.o: logicop.cpp.o
.PHONY : logicop.o

# target to build an object file
logicop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/logicop.cpp.o
.PHONY : logicop.cpp.o

logicop.i: logicop.cpp.i
.PHONY : logicop.i

# target to preprocess a source file
logicop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/logicop.cpp.i
.PHONY : logicop.cpp.i

logicop.s: logicop.cpp.s
.PHONY : logicop.s

# target to generate assembly for a file
logicop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/logicop.cpp.s
.PHONY : logicop.cpp.s

multi_vertex_texture_shader.o: multi_vertex_texture_shader.cpp.o
.PHONY : multi_vertex_texture_shader.o

# target to build an object file
multi_vertex_texture_shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/multi_vertex_texture_shader.cpp.o
.PHONY : multi_vertex_texture_shader.cpp.o

multi_vertex_texture_shader.i: multi_vertex_texture_shader.cpp.i
.PHONY : multi_vertex_texture_shader.i

# target to preprocess a source file
multi_vertex_texture_shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/multi_vertex_texture_shader.cpp.i
.PHONY : multi_vertex_texture_shader.cpp.i

multi_vertex_texture_shader.s: multi_vertex_texture_shader.cpp.s
.PHONY : multi_vertex_texture_shader.s

# target to generate assembly for a file
multi_vertex_texture_shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/multi_vertex_texture_shader.cpp.s
.PHONY : multi_vertex_texture_shader.cpp.s

single_vertex_texture_shader.o: single_vertex_texture_shader.cpp.o
.PHONY : single_vertex_texture_shader.o

# target to build an object file
single_vertex_texture_shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/single_vertex_texture_shader.cpp.o
.PHONY : single_vertex_texture_shader.cpp.o

single_vertex_texture_shader.i: single_vertex_texture_shader.cpp.i
.PHONY : single_vertex_texture_shader.i

# target to preprocess a source file
single_vertex_texture_shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/single_vertex_texture_shader.cpp.i
.PHONY : single_vertex_texture_shader.cpp.i

single_vertex_texture_shader.s: single_vertex_texture_shader.cpp.s
.PHONY : single_vertex_texture_shader.s

# target to generate assembly for a file
single_vertex_texture_shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/single_vertex_texture_shader.cpp.s
.PHONY : single_vertex_texture_shader.cpp.s

src/GLSLProgram.o: src/GLSLProgram.cpp.o
.PHONY : src/GLSLProgram.o

# target to build an object file
src/GLSLProgram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/src/GLSLProgram.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/src/GLSLProgram.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/src/GLSLProgram.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/src/GLSLProgram.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/src/GLSLProgram.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/src/GLSLProgram.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/src/GLSLProgram.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/src/GLSLProgram.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/src/GLSLProgram.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/src/GLSLProgram.cpp.o
.PHONY : src/GLSLProgram.cpp.o

src/GLSLProgram.i: src/GLSLProgram.cpp.i
.PHONY : src/GLSLProgram.i

# target to preprocess a source file
src/GLSLProgram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/src/GLSLProgram.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/src/GLSLProgram.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/src/GLSLProgram.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/src/GLSLProgram.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/src/GLSLProgram.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/src/GLSLProgram.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/src/GLSLProgram.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/src/GLSLProgram.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/src/GLSLProgram.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/src/GLSLProgram.cpp.i
.PHONY : src/GLSLProgram.cpp.i

src/GLSLProgram.s: src/GLSLProgram.cpp.s
.PHONY : src/GLSLProgram.s

# target to generate assembly for a file
src/GLSLProgram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/src/GLSLProgram.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/src/GLSLProgram.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/src/GLSLProgram.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/src/GLSLProgram.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/src/GLSLProgram.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/src/GLSLProgram.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/src/GLSLProgram.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/src/GLSLProgram.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/src/GLSLProgram.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/src/GLSLProgram.cpp.s
.PHONY : src/GLSLProgram.cpp.s

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/stb_image.o: src/stb_image.cpp.o
.PHONY : src/stb_image.o

# target to build an object file
src/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/src/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/src/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/src/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/src/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/src/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/src/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/src/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/src/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/src/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/src/stb_image.cpp.o
.PHONY : src/stb_image.cpp.o

src/stb_image.i: src/stb_image.cpp.i
.PHONY : src/stb_image.i

# target to preprocess a source file
src/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/src/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/src/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/src/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/src/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/src/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/src/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/src/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/src/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/src/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/src/stb_image.cpp.i
.PHONY : src/stb_image.cpp.i

src/stb_image.s: src/stb_image.cpp.s
.PHONY : src/stb_image.s

# target to generate assembly for a file
src/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/src/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/single_vertex_texture_shader.dir/build.make CMakeFiles/single_vertex_texture_shader.dir/src/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blending.dir/build.make CMakeFiles/blending.dir/src/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logicop.dir/build.make CMakeFiles/logicop.dir/src/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/src/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basicPoints.dir/build.make CMakeFiles/basicPoints.dir/src/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/depth_test.dir/build.make CMakeFiles/depth_test.dir/src/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feed_back.dir/build.make CMakeFiles/feed_back.dir/src/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complex.dir/build.make CMakeFiles/complex.dir/src/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_vertex_texture_shader.dir/build.make CMakeFiles/multi_vertex_texture_shader.dir/src/stb_image.cpp.s
.PHONY : src/stb_image.cpp.s

template.o: template.cpp.o
.PHONY : template.o

# target to build an object file
template.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/template.cpp.o
.PHONY : template.cpp.o

template.i: template.cpp.i
.PHONY : template.i

# target to preprocess a source file
template.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/template.cpp.i
.PHONY : template.cpp.i

template.s: template.cpp.s
.PHONY : template.s

# target to generate assembly for a file
template.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template.dir/build.make CMakeFiles/template.dir/template.cpp.s
.PHONY : template.cpp.s

vertex_texture.o: vertex_texture.cpp.o
.PHONY : vertex_texture.o

# target to build an object file
vertex_texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/vertex_texture.cpp.o
.PHONY : vertex_texture.cpp.o

vertex_texture.i: vertex_texture.cpp.i
.PHONY : vertex_texture.i

# target to preprocess a source file
vertex_texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/vertex_texture.cpp.i
.PHONY : vertex_texture.cpp.i

vertex_texture.s: vertex_texture.cpp.s
.PHONY : vertex_texture.s

# target to generate assembly for a file
vertex_texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vertex_texture.dir/build.make CMakeFiles/vertex_texture.dir/vertex_texture.cpp.s
.PHONY : vertex_texture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... basicPoints"
	@echo "... blending"
	@echo "... complex"
	@echo "... depth_test"
	@echo "... feed_back"
	@echo "... logicop"
	@echo "... multi_vertex_texture_shader"
	@echo "... single_vertex_texture_shader"
	@echo "... template"
	@echo "... vertex_texture"
	@echo "... basicPoints.o"
	@echo "... basicPoints.i"
	@echo "... basicPoints.s"
	@echo "... blending.o"
	@echo "... blending.i"
	@echo "... blending.s"
	@echo "... complex.o"
	@echo "... complex.i"
	@echo "... complex.s"
	@echo "... depth_test.o"
	@echo "... depth_test.i"
	@echo "... depth_test.s"
	@echo "... feed_back.o"
	@echo "... feed_back.i"
	@echo "... feed_back.s"
	@echo "... logicop.o"
	@echo "... logicop.i"
	@echo "... logicop.s"
	@echo "... multi_vertex_texture_shader.o"
	@echo "... multi_vertex_texture_shader.i"
	@echo "... multi_vertex_texture_shader.s"
	@echo "... single_vertex_texture_shader.o"
	@echo "... single_vertex_texture_shader.i"
	@echo "... single_vertex_texture_shader.s"
	@echo "... src/GLSLProgram.o"
	@echo "... src/GLSLProgram.i"
	@echo "... src/GLSLProgram.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/stb_image.o"
	@echo "... src/stb_image.i"
	@echo "... src/stb_image.s"
	@echo "... template.o"
	@echo "... template.i"
	@echo "... template.s"
	@echo "... vertex_texture.o"
	@echo "... vertex_texture.i"
	@echo "... vertex_texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

